# Generated by Django 4.2.7 on 2023-12-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.carbrand'),
        ),
    ]
