# Generated by Django 4.2.7 on 2023-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0002_alter_cardetails_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_details/media/uploads/'),
        ),
    ]
